### ISSUE TITLE
Add Preference page 

### ISSUE THREAD

**Issue by Pitoche** [quinone/password-manager#42]
Add Preference pages  and link fields to DB

**Comment by quinone** [comment]
# What preferences do we want?

## Custom time limit for auto log out
I would like to increase the time before logging out.
Maybe adding a field for that? We can set the default to 5 minutes?

## Toggle light/dark mode
Using bootstrap we should be easily able to add a toggle light and dark mode.
By adding an if statement to base.html it should be as simple as swapping "dark" and "light" in the <html> tag 

```
<html lang="en" data-bs-theme="dark">
<html lang="en" data-bs-theme="light">
```

**Comment by Pitoche** [comment]
I added some fields back on the 4th JUNNE but now I am  not getting anything

**Comment by quinone** [comment]
So the blueprint for /settings needed to be added to create_app().
 
Yeah, are you looking to use flask-login? Was that from you or @Rachie94 ?

**Comment by Pitoche** [comment]
Mine was just a page with 2 fields as I had little time. but right now I am getting an error

**Comment by quinone** [comment]
This wasn't you?
``` python
login_manager = LoginManager()
login_manager.init_app(app)

bp = Blueprint("settings", __name__, url_prefix="/setting", template_folder="templates")


@bp.route("/", methods=["GET", "POST"])
@login_required
def settings():
    if request.method == "POST":
        vault_timeout = request.form.get("vaultTimeout", default="00:05:00")
        theme_id = request.form.get("themeId", default="light")
        settings_html = request.form.get(
            "settingsHtml", default=""
        )  # Get HTML content from the form

        try:
            conn = get_db()
            cursor = conn.cursor()
            cursor.execute(
                "REPLACE INTO preferences (user_id, vault_timeout, theme_id, settings_html) VALUES (?, ?, ?, ?)",
                (
                    current_user.id,
                    vault_timeout,
                    theme_id,
                    settings_html,
                ),  # Use current_user.id to get user_id
            )
            conn.commit()
            cursor.close()
            conn.close()
            flash("Preferences saved successfully", "success")
        except Exception as e:
            flash(f"Failed to save preferences: {str(e)}", "danger")

        return redirect(url_for("settings.settings"))

    return render_template("settings.html")```

**Comment by Pitoche** [comment]
I think so..

**Comment by quinone** [comment]
Think its fixed now. Try git fetch on development branch.
I've commented out flask-login. Its a great module but would require a large refactoring if we are going to use it fully.

**Comment by Pitoche** [comment]
I now have 2 "settings" links and both work Not sure where the "other" is coming from

**Comment by quinone** [comment]
I updated to use `{ URL_for('settings.settings')}` and forgot to remove the old link.
Ill remove in next push

12 Jun 2024 21:23:29 Angel De Luis ***@***.***>:
